"""Offline tests for um nexus: no network, no API key, no game.

    uv run --with pytest pytest -q
"""
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from um import backup  # noqa: E402

def test_version_compare_ignores_mo2_padding():
    # MO2 stores every version padded to x.y.z.w; without stripping it, a whole modlist read "ahead of Nexus"
    from um import nexus
    for local, remote, want in [("1.1.0.0", "1.1", "same"), ("1.0.0.0", "1.0", "same"), ("1.0.0.0", "1", "same"),
                                ("4.2.6a", "4.2.6a", "same"), ("v6.9", "6.9", "same"),
                                ("1.0.0.0", "1.1", "newer"), ("5.9.2.0", "6.0.4", "newer"),
                                ("1.2.0.0", "1.1", "older"),
                                ("5.8.0.0a", "5.8", "differs"), ("1.0.0.0", "1.0b", "differs"),
                                ("", "1.0", "differs"), ("1.0", "", "differs")]:
        assert nexus.compare_versions(local, remote) == want, (local, remote)


def test_mod_uid_packs_game_and_mod():
    # the batch query takes uids, not (game, mod) pairs
    from um import nexus
    assert nexus.uid(1704, 272) == str((1704 << 32) | 272) == "7318624272656"
    assert nexus.file_bytes({"sizeInBytes": "2693003"}) == 2693003    # BigInt arrives as a string
    assert nexus.file_bytes({"size": 2630}) == 2630 * 1024            # size is in KB
    assert nexus.file_bytes({}) == 0


def mo2_instance(root, mods, profile="Default", enabled=None):
    """A miniature Mod Organizer 2 instance: ModOrganizer.ini, mods/<name>/meta.ini, a profile modlist."""
    (root / "profiles" / profile).mkdir(parents=True, exist_ok=True)
    root.joinpath("ModOrganizer.ini").write_text(
        "[General]\ngameName=Skyrim Special Edition\n"
        "selected_profile=@ByteArray(" + profile + ")\n", encoding="utf-8")
    for name, fields in mods.items():
        d = root / "mods" / name
        d.mkdir(parents=True, exist_ok=True)
        body = "[General]\n" + "".join(f"{k}={v}\n" for k, v in fields.items())
        # MO2 pastes the whole Nexus description in here; real files run to tens of KB
        body += 'nexusDescription="' + ("padding " * 4000) + '"\n'
        d.joinpath("meta.ini").write_text(body, encoding="utf-8")
    lines = [("+" if enabled is None or n in enabled else "-") + n for n in mods]
    (root / "profiles" / profile / "modlist.txt").write_text(
        "# generated by Mod Organizer\n" + "\n".join(lines) + "\n-Some Separator_separator\n", encoding="utf-8")


def test_installed_reads_mo2_metadata(tmp_path):
    from um import nexus
    mo2 = tmp_path / "LoreRim"
    mo2_instance(mo2, {
        "Alternate Start": dict(gameName="SkyrimSE", modid="272", version="4.2.0.0",
                                installationFile="Alternate Start-272-4-2-123456789.7z", repository="Nexus"),
        "Switched Off": dict(gameName="SkyrimSE", modid="12604", version="6.0.0.0", repository="Nexus"),
        "Hand Built": dict(gameName="SkyrimSE", modid="0", version="1.0"),          # no Nexus id: skipped
    }, enabled={"Alternate Start"})

    everything = nexus.installed(str(mo2))
    assert [m["folder"] for m in everything] == ["Alternate Start", "Switched Off"]
    assert everything[0]["mod_id"] == 272 and everything[0]["version"] == "4.2.0.0"
    assert everything[0]["enabled"] is True and everything[1]["enabled"] is False
    assert everything[0]["file"].endswith(".7z")                 # read past the padding, not truncated

    on = nexus.installed(str(mo2), enabled_only=True)
    assert [m["folder"] for m in on] == ["Alternate Start"]
    assert nexus.mo2_setting(mo2 / "ModOrganizer.ini", "selected_profile") == "Default"   # @ByteArray unwrapped


def test_updates_reports_rather_than_skips(tmp_path, monkeypatch):
    from um import nexus
    mo2 = tmp_path / "inst"
    mo2_instance(mo2, {
        "Needs Update": dict(gameName="SkyrimSE", modid="272", version="4.1.0.0", repository="Nexus"),
        "Up To Date": dict(gameName="SkyrimSE", modid="12604", version="6.11.0.0", repository="Nexus"),
        "Skipped In MO2": dict(gameName="SkyrimSE", modid="999", version="1.0", ignoredVersion="2.0",
                               repository="Nexus"),
        "Gone From Nexus": dict(gameName="SkyrimSE", modid="4242", version="1.0", repository="Nexus"),
        "Mystery Game": dict(gameName="NoSuchGame", modid="7", version="1.0", repository="Nexus"),
    })
    sse = {"id": 1704, "name": "Skyrim SE", "domainName": "skyrimspecialedition"}
    monkeypatch.setattr(nexus, "resolve_game",
                        lambda t: sse if str(t).lower() in ("skyrimse", "skyrimspecialedition")
                        else nexus.die("no game " + str(t)))
    remote = {272: dict(modId=272, name="Alternate Start", version="4.2.6a", category="Gameplay",
                        status="published", updatedAt="2026-03-08T00:00:00Z"),
              12604: dict(modId=12604, name="SkyUI", version="6.11", category="User Interface",
                          status="published", updatedAt="2026-05-01T00:00:00Z"),
              999: dict(modId=999, name="Skipped", version="2.0", category="Gameplay",
                        status="published", updatedAt="2026-01-01T00:00:00Z")}
    monkeypatch.setattr(nexus, "fetch_mods",
                        lambda game_id, ids, progress=False: {i: remote[i] for i in ids if i in remote})

    res = nexus.updates(str(mo2), progress=False)
    state = {r["folder"]: r["state"] for r in res["mods"]}
    assert state == {"Needs Update": "newer", "Up To Date": "same", "Skipped In MO2": "ignored"}
    unresolved = {u["folder"]: u["why"] for u in res["unresolved"]}
    assert set(unresolved) == {"Gone From Nexus", "Mystery Game"}       # reported, never silently dropped
    assert "removed, hidden or wrong" in unresolved["Gone From Nexus"]
    assert "NoSuchGame" in unresolved["Mystery Game"]
    assert res["mods"][0]["folder"] == "Needs Update"                   # updates sort to the top


@pytest.mark.parametrize("url,want", [
    ("nxm://skyrimspecialedition/mods/272/files/749043?key=abc&expires=123",
     dict(domain="skyrimspecialedition", mod_id=272, file_id=749043, key="abc", expires="123")),
    ("nxm://fallout4/mods/1/files/2", dict(domain="fallout4", mod_id=1, file_id=2, key=None, expires=None)),
])
def test_nxm_url_parsing(url, want):
    from um import nexus
    assert nexus.nxm_parse(url) == want


@pytest.mark.parametrize("bad", ["https://nexusmods.com/skyrimspecialedition/mods/272",
                                 "nxm://skyrimspecialedition/collections/abc",
                                 "nxm://skyrimspecialedition/mods/272"])
def test_nxm_url_rejects_other_shapes(bad):
    from um import nexus
    with pytest.raises(SystemExit):
        nexus.nxm_parse(bad)


def test_nexus_filename_carries_the_mod_id():
    from um import nexus
    got = nexus.from_filename(Path("(2)Barbarian Bodypaints - CBBE-31826-1-0-1579138592.7z"))
    assert got["mod_id"] == 31826 and got["version"] == "1.0"
    assert got["name"] == "(2)Barbarian Bodypaints - CBBE"
    assert nexus.from_filename(Path("hand-made-thing.zip")) == {}


def test_api_key_comes_only_from_the_environment(tmp_path, monkeypatch):
    from um import nexus
    monkeypatch.delenv("NEXUS_API_KEY", raising=False)
    monkeypatch.delenv("NEXUS_API_KEY_FILE", raising=False)
    (tmp_path / ".env").write_text("NEXUS_API_KEY=should-not-be-read\n", encoding="utf-8")
    monkeypatch.chdir(tmp_path)
    assert nexus.api_key(required=False) is None          # a .env in the cwd is not a key you chose to use
    with pytest.raises(SystemExit):
        nexus.api_key()
    keyfile = tmp_path / "key.txt"
    keyfile.write_text("  from-a-file  \n", encoding="utf-8")
    monkeypatch.setenv("NEXUS_API_KEY_FILE", str(keyfile))
    assert nexus.api_key() == "from-a-file"
    monkeypatch.setenv("NEXUS_API_KEY", "from-the-env")
    assert nexus.api_key() == "from-the-env"              # the variable wins over the file


@pytest.mark.parametrize("member", ["../escaped.txt", "a/../../escaped.txt", "/abs/escaped.txt",
                                    "C:/abs/escaped.txt", "..\\escaped.txt"])
def test_install_refuses_an_archive_that_writes_outside(tmp_path, member):
    # a Nexus download is a stranger's archive, and MO2's own mods folder is the target
    from um import nexus
    archive = tmp_path / "Evil Mod-123-1-0-123456789.zip"
    with backup.zipfile.ZipFile(archive, "w") as z:
        z.writestr("meshes/fine.nif", b"ok")
        z.writestr(member, b"pwned")
    mods = tmp_path / "mods"
    with pytest.raises(SystemExit):
        nexus.install(str(archive), str(mods), yes=True)
    assert not list(tmp_path.rglob("escaped.txt"))


def test_install_unpacks_and_leaves_meta_for_update_checking(tmp_path, monkeypatch):
    from um import nexus
    archive = tmp_path / "Alternate Start-272-4-2-6-1579138592.zip"
    with backup.zipfile.ZipFile(archive, "w") as z:
        z.writestr("Alternate Start.esp", b"TES4")
        z.writestr("scripts/thing.pex", b"pex")
    mods = tmp_path / "mods"
    monkeypatch.setattr(nexus, "resolve_game", lambda t: {"id": 1704, "name": "Skyrim Special Edition",
                                                          "domainName": "skyrimspecialedition"})

    with pytest.raises(SystemExit):                         # writing into a loaded mods folder is confirmed
        nexus.install(str(archive), str(mods))

    target = nexus.install(str(archive), str(mods), game="skyrimspecialedition", yes=True)
    assert (target / "Alternate Start.esp").read_bytes() == b"TES4"
    assert (target / "scripts" / "thing.pex").exists()
    meta = nexus.read_meta(target / "meta.ini")
    assert meta["modid"] == "272" and meta["version"] == "4.2.6" and meta["repository"] == "Nexus"
    assert nexus.installed(str(mods))[0]["mod_id"] == 272    # the loop closes: updates now tracks it
